server:
  port: 8888

spring:
  application:
    name: microservices-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gadams00/build-microservices-poc-config